
x-common-variables: &common-variables
  REDIS_CACHE_URL: 'redis://redis:6379/1'
  SECRET_KEY: 'CHANGE_ME_LOCAL_DEV_ONLY'
  DEPLOYMENT_CONTEXT: "local"
  DEBUG: "True"
  CELERY_BROKER_URL: 'redis://redis:6379/0'
  CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
  CELERY_ENABLED: "True"
services:
  hostmods:
    build:
      context: .
      dockerfile: Dockerfile.hostmods
    volumes:
      - .:/workspace:cached

  web:
    user: $UID:$GID
    tmpfs: /tmp
    build:
      context: web/
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
      - dev_node_modules:/app/node_modules
    ports:
      - 3000:3000

  api:
    user: $UID:$GID
    build:
      context: api/
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    environment:
      <<: *common-variables

  celery-worker:
    user: $UID:$GID
    build:
      context: api/
      dockerfile: Dockerfile.dev
    entrypoint: /app/bin/celery-worker
    volumes:
      - ./api:/app
    environment:
      <<: *common-variables
    depends_on:
      - api

  celery-beat:
    user: $UID:$GID
    build:
      context: api/
      dockerfile: Dockerfile.dev
    entrypoint: /app/bin/celery-beat
    volumes:
      - ./api:/app
    environment:
      <<: *common-variables
    depends_on:
      - api

  redis:
    user: $UID:$GID
    image: redis:latest
    ports:
      - 6379:6379


volumes:
  dev_node_modules:
  dev_nuxt:
  dev_pnpm_store: