# Generated by Django 5.2.4 on 2025-07-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Admin"), (1, "User")], default=1
            ),
        ),
    ]
