"""
Django settings for Starter project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import environ

BASE_DIR = Path(__file__).resolve().parent.parent.parent

# env
env = environ.Env(
    DEBUG=(bool, False),
    USE_WSGI=(bool, False),
    CELERY_BROKER_URL=(str, "redis://redis:6379/0"),
    CELERY_RESULT_BACKEND=(str, "redis://redis:6379/0"),
    CELERY_ENABLED=(bool, False),
    SECRET_KEY=(str, "veVah6aeca1fiepaigee0Waingai5goo-INSECURE!"),
    REDIS_CACHE_URL=(str, "redis://redis:6379/1"),
)


# Databases
PG_NAME = env("PG_NAME", default=None)
PG_USER = env("PG_USER", default=None)
PG_PASSWORD = env("PG_PASSWORD", default=None)
PG_HOST = env("PG_HOST", default=None)
PG_PORT = env("PG_PORT", default=None)


ALLOWED_HOSTS = ["*"]
DEBUG = env("DEBUG")
SECRET_KEY = env("SECRET_KEY")


INSTALLED_APPS = [
    "daphne",
    # default
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd party
    "rest_framework",
    "rest_framework.authtoken",
    "dj_rest_auth",
    "drf_spectacular",
    "channels",
    # local
    "accounts.apps.AccountsConfig",
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Starter API",
    "DESCRIPTION": "Starter API",
    "VERSION": "0.0.1",
    "SERVE_INCLUDE_SCHEMA": False,
    # "SERVE_PERMISSIONS": ["accounts.permissions.IsAdmin"]
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [env("REDIS_CACHE_URL")],
        },
    },
}

# Locale
LANGUAGE_CODE = "en-us"
TIME_ZONE = "CET"
USE_TZ = True
USE_I18N = True

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
