FROM python:3.12-bookworm

# Name it
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBUG=True

WORKDIR /app
COPY . .

RUN apt update

# python
RUN pip install -r requirements.txt --no-cache-dir

EXPOSE 8000

ENTRYPOINT ["bash"]

CMD ["bin/entrypoint-dev"]
